import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/query-provider";
import Navbar from "@/components/navbar/Navbar";
import ReduxProvider from "@/providers/redux-provider";
import Footer from "@/components/footer/Footer";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar/>
          <main>{children}</main>
          <Footer/>
        </body>
      </html>
      </ReduxProvider>
    </QueryProvider>
  );
}
